"""
AssistantState: Core data structure for the LangGraph orchestration.

This TypedDict defines all state fields that flow through the graph nodes.
Using TypedDict ensures type safety and clear contracts between nodes.
"""

from typing import Any, Dict, List, Optional, TypedDict


class AssistantState(TypedDict, total=False):
    """Complete state structure for the ERP AI Assistant workflow.
    
    Fields:
        question: Original user question.
        intent: Classified intent (GET, AGGREGATE, FILTER).
        domain: Inferred business domain (commercial, stock, finance, rh, achat, general).
        endpoint_candidates: Scored endpoints after retrieval.
        selected_endpoints: Final list of endpoints to call.
        selected_endpoint: Primary endpoint (first of selected_endpoints).
        extracted_params: Parameters extracted from question + LLM routing.
        api_result_path: Path to cached raw API result JSON.
        collection_name: MongoDB collection containing API results.
        data_headers: List of field names in the data collection.
        mongodb_query: Aggregation pipeline generated by Llama for NoSQL query.
        mongodb_query_generated: Whether Llama successfully generated a query.
        query_results: Results from MongoDB aggregation pipeline execution.
        result_count: Number of results from NoSQL query.
        filtered_result: Processed & filtered result (records[:20] + metadata).
        answer: Final natural language response from LLM.
        confidence: Confidence score (0.0-1.0).
        errors: List of error messages accumulated through execution.
    """
    
    question: str
    intent: str  # "GET", "AGGREGATE", "FILTER"
    domain: str  # "commercial", "stock", "finance", "rh", "achat", "general"
    endpoint_candidates: List[Dict[str, Any]]
    selected_endpoints: List[Dict[str, Any]]
    selected_endpoint: Optional[Dict[str, Any]]
    extracted_params: Dict[str, Any]
    api_result_path: str
    collection_name: Optional[str]
    data_headers: List[str]
    mongodb_query: Optional[List[Dict[str, Any]]]
    mongodb_query_generated: bool
    query_results: List[Dict[str, Any]]
    result_count: int
    filtered_result: Dict[str, Any]
    answer: str
    confidence: float
    errors: List[str]
